baseURL = "https://lassediercks.de/"
languageCode = "de"
title = "Lasse Diercks"
GoogleAnalytics = "UA-25133681-1"

[params]
  description = "Independent Web Advocate"
  og_image = "/img/open-graph.png"


uglyurls = true
#[permalinks]
post = "/:year/:month/:day/:slug/"