baseURL = "https://lassediercks.de/"
languageCode = "de"
title = "Lasse Diercks"
GoogleAnalytics = "UA-25133681-1"

params:
  author: Lasse Diercks
  description: I help people to succeed in the web.
